# Generated by Django 4.0.3 on 2022-04-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=30)),
                ('blog_header', models.CharField(max_length=100)),
                ('blog_content', models.CharField(max_length=300)),
            ],
        ),
    ]
